// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compensation.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendCompensationLog = `-- name: AppendCompensationLog :one
INSERT INTO compensation_logs (
    transaction_id,
    participant_id,
    sequence_no,
    action_type,
    compensation_endpoint,
    request_payload,
    status
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    'pending'
)
RETURNING id, transaction_id, participant_id, sequence_no, action_type, compensation_endpoint, request_payload, response_payload, status, error_message, retry_count, executed_at, created_at, updated_at, deleted_at
`

type AppendCompensationLogParams struct {
	TransactionID        uuid.UUID `json:"transaction_id"`
	ParticipantID        uuid.UUID `json:"participant_id"`
	SequenceNo           int64     `json:"sequence_no"`
	ActionType           string    `json:"action_type"`
	CompensationEndpoint string    `json:"compensation_endpoint"`
	RequestPayload       []byte    `json:"request_payload"`
}

func (q *Queries) AppendCompensationLog(ctx context.Context, arg AppendCompensationLogParams) (CompensationLog, error) {
	row := q.db.QueryRow(ctx, appendCompensationLog,
		arg.TransactionID,
		arg.ParticipantID,
		arg.SequenceNo,
		arg.ActionType,
		arg.CompensationEndpoint,
		arg.RequestPayload,
	)
	var i CompensationLog
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ParticipantID,
		&i.SequenceNo,
		&i.ActionType,
		&i.CompensationEndpoint,
		&i.RequestPayload,
		&i.ResponsePayload,
		&i.Status,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.ExecutedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const completeCompensation = `-- name: CompleteCompensation :exec
UPDATE compensation_logs
SET
    status = 'completed',
    response_payload = $2,
    executed_at = now()
WHERE id = $1
`

type CompleteCompensationParams struct {
	ID              uuid.UUID `json:"id"`
	ResponsePayload []byte    `json:"response_payload"`
}

func (q *Queries) CompleteCompensation(ctx context.Context, arg CompleteCompensationParams) error {
	_, err := q.db.Exec(ctx, completeCompensation, arg.ID, arg.ResponsePayload)
	return err
}

const failCompensation = `-- name: FailCompensation :exec
UPDATE compensation_logs
SET
    status = 'failed',
    error_message = $2,
    retry_count = retry_count + 1
WHERE id = $1
`

type FailCompensationParams struct {
	ID           uuid.UUID   `json:"id"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) FailCompensation(ctx context.Context, arg FailCompensationParams) error {
	_, err := q.db.Exec(ctx, failCompensation, arg.ID, arg.ErrorMessage)
	return err
}

const getPendingCompensations = `-- name: GetPendingCompensations :many
SELECT id, transaction_id, participant_id, sequence_no, action_type, compensation_endpoint, request_payload, response_payload, status, error_message, retry_count, executed_at, created_at, updated_at, deleted_at
FROM compensation_logs
WHERE status IN ('pending', 'failed')
ORDER BY sequence_no DESC
LIMIT $1
`

func (q *Queries) GetPendingCompensations(ctx context.Context, limit int32) ([]CompensationLog, error) {
	rows, err := q.db.Query(ctx, getPendingCompensations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompensationLog
	for rows.Next() {
		var i CompensationLog
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.ParticipantID,
			&i.SequenceNo,
			&i.ActionType,
			&i.CompensationEndpoint,
			&i.RequestPayload,
			&i.ResponsePayload,
			&i.Status,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.ExecutedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCompensationRunning = `-- name: MarkCompensationRunning :exec
UPDATE compensation_logs
SET status = 'running'
WHERE id = $1
`

func (q *Queries) MarkCompensationRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markCompensationRunning, id)
	return err
}
