// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coordinator.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeTransaction = `-- name: CompleteTransaction :exec
UPDATE distributed_transactions
SET
    completed_at = now(),
    recovery_needed = false,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) CompleteTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, completeTransaction, id)
	return err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO distributed_transactions (
    id,
    correlation_id,
    idempotency_key,
    state,
    metadata
)
VALUES (
    $1,
    $2,
    $3,
    'initiated',
    $4
)
RETURNING id, correlation_id, idempotency_key, state, recovery_needed, recovery_attempts, last_recovery_at, coordinator_instance_id, lease_expires_at, prepare_deadline, commit_deadline, version, metadata, created_at, updated_at, completed_at, deleted_at
`

type CreateTransactionParams struct {
	ID             uuid.UUID   `json:"id"`
	CorrelationID  pgtype.Text `json:"correlation_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	Metadata       []byte      `json:"metadata"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (DistributedTransaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.CorrelationID,
		arg.IdempotencyKey,
		arg.Metadata,
	)
	var i DistributedTransaction
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.IdempotencyKey,
		&i.State,
		&i.RecoveryNeeded,
		&i.RecoveryAttempts,
		&i.LastRecoveryAt,
		&i.CoordinatorInstanceID,
		&i.LeaseExpiresAt,
		&i.PrepareDeadline,
		&i.CommitDeadline,
		&i.Version,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, correlation_id, idempotency_key, state, recovery_needed, recovery_attempts, last_recovery_at, coordinator_instance_id, lease_expires_at, prepare_deadline, commit_deadline, version, metadata, created_at, updated_at, completed_at, deleted_at
FROM distributed_transactions
WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id uuid.UUID) (DistributedTransaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i DistributedTransaction
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.IdempotencyKey,
		&i.State,
		&i.RecoveryNeeded,
		&i.RecoveryAttempts,
		&i.LastRecoveryAt,
		&i.CoordinatorInstanceID,
		&i.LeaseExpiresAt,
		&i.PrepareDeadline,
		&i.CommitDeadline,
		&i.Version,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const transitionTransactionState = `-- name: TransitionTransactionState :one
UPDATE distributed_transactions
SET
    state = $2,
    version = version + 1,
    updated_at = now()
WHERE id = $1
AND version = $3
RETURNING id, correlation_id, idempotency_key, state, recovery_needed, recovery_attempts, last_recovery_at, coordinator_instance_id, lease_expires_at, prepare_deadline, commit_deadline, version, metadata, created_at, updated_at, completed_at, deleted_at
`

type TransitionTransactionStateParams struct {
	ID      uuid.UUID `json:"id"`
	State   TxState   `json:"state"`
	Version int64     `json:"version"`
}

func (q *Queries) TransitionTransactionState(ctx context.Context, arg TransitionTransactionStateParams) (DistributedTransaction, error) {
	row := q.db.QueryRow(ctx, transitionTransactionState, arg.ID, arg.State, arg.Version)
	var i DistributedTransaction
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.IdempotencyKey,
		&i.State,
		&i.RecoveryNeeded,
		&i.RecoveryAttempts,
		&i.LastRecoveryAt,
		&i.CoordinatorInstanceID,
		&i.LeaseExpiresAt,
		&i.PrepareDeadline,
		&i.CommitDeadline,
		&i.Version,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}
