// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendTransactionEvent = `-- name: AppendTransactionEvent :exec
INSERT INTO transaction_events (
    transaction_id,
    participant_id,
    event_type,
    event_data
)
VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type AppendTransactionEventParams struct {
	TransactionID uuid.UUID   `json:"transaction_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
	EventType     string      `json:"event_type"`
	EventData     []byte      `json:"event_data"`
}

func (q *Queries) AppendTransactionEvent(ctx context.Context, arg AppendTransactionEventParams) error {
	_, err := q.db.Exec(ctx, appendTransactionEvent,
		arg.TransactionID,
		arg.ParticipantID,
		arg.EventType,
		arg.EventData,
	)
	return err
}

const getTransactionTimeline = `-- name: GetTransactionTimeline :many
SELECT id, transaction_id, participant_id, event_type, event_data, created_at
FROM transaction_events
WHERE transaction_id = $1
ORDER BY created_at
`

func (q *Queries) GetTransactionTimeline(ctx context.Context, transactionID uuid.UUID) ([]TransactionEvent, error) {
	rows, err := q.db.Query(ctx, getTransactionTimeline, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionEvent
	for rows.Next() {
		var i TransactionEvent
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.ParticipantID,
			&i.EventType,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
