// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leases.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acquireRecoveryLease = `-- name: AcquireRecoveryLease :one
UPDATE distributed_transactions
SET
    coordinator_instance_id = $2,
    lease_expires_at = now() + interval '30 seconds'
WHERE id = $1
AND (
    lease_expires_at IS NULL
    OR lease_expires_at < now()
)
RETURNING id, correlation_id, idempotency_key, state, recovery_needed, recovery_attempts, last_recovery_at, coordinator_instance_id, lease_expires_at, prepare_deadline, commit_deadline, version, metadata, created_at, updated_at, completed_at, deleted_at
`

type AcquireRecoveryLeaseParams struct {
	ID                    uuid.UUID   `json:"id"`
	CoordinatorInstanceID pgtype.Text `json:"coordinator_instance_id"`
}

func (q *Queries) AcquireRecoveryLease(ctx context.Context, arg AcquireRecoveryLeaseParams) (DistributedTransaction, error) {
	row := q.db.QueryRow(ctx, acquireRecoveryLease, arg.ID, arg.CoordinatorInstanceID)
	var i DistributedTransaction
	err := row.Scan(
		&i.ID,
		&i.CorrelationID,
		&i.IdempotencyKey,
		&i.State,
		&i.RecoveryNeeded,
		&i.RecoveryAttempts,
		&i.LastRecoveryAt,
		&i.CoordinatorInstanceID,
		&i.LeaseExpiresAt,
		&i.PrepareDeadline,
		&i.CommitDeadline,
		&i.Version,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const renewRecoveryLease = `-- name: RenewRecoveryLease :exec
UPDATE distributed_transactions
SET
    lease_expires_at = now() + interval '30 seconds'
WHERE id = $1
AND coordinator_instance_id = $2
`

type RenewRecoveryLeaseParams struct {
	ID                    uuid.UUID   `json:"id"`
	CoordinatorInstanceID pgtype.Text `json:"coordinator_instance_id"`
}

func (q *Queries) RenewRecoveryLease(ctx context.Context, arg RenewRecoveryLeaseParams) error {
	_, err := q.db.Exec(ctx, renewRecoveryLease, arg.ID, arg.CoordinatorInstanceID)
	return err
}
