// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CompensationStatus string

const (
	CompensationStatusPending   CompensationStatus = "pending"
	CompensationStatusRunning   CompensationStatus = "running"
	CompensationStatusCompleted CompensationStatus = "completed"
	CompensationStatusFailed    CompensationStatus = "failed"
)

func (e *CompensationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompensationStatus(s)
	case string:
		*e = CompensationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CompensationStatus: %T", src)
	}
	return nil
}

type NullCompensationStatus struct {
	CompensationStatus CompensationStatus `json:"compensation_status"`
	Valid              bool               `json:"valid"` // Valid is true if CompensationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompensationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CompensationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompensationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompensationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompensationStatus), nil
}

type ParticipantState string

const (
	ParticipantStateRegistered      ParticipantState = "registered"
	ParticipantStatePrepareSent     ParticipantState = "prepare_sent"
	ParticipantStatePrepared        ParticipantState = "prepared"
	ParticipantStatePrepareFailed   ParticipantState = "prepare_failed"
	ParticipantStateCommitSent      ParticipantState = "commit_sent"
	ParticipantStateCommitted       ParticipantState = "committed"
	ParticipantStateAbortSent       ParticipantState = "abort_sent"
	ParticipantStateAborted         ParticipantState = "aborted"
	ParticipantStateHeuristicCommit ParticipantState = "heuristic_commit"
	ParticipantStateHeuristicAbort  ParticipantState = "heuristic_abort"
	ParticipantStateTimeout         ParticipantState = "timeout"
)

func (e *ParticipantState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ParticipantState(s)
	case string:
		*e = ParticipantState(s)
	default:
		return fmt.Errorf("unsupported scan type for ParticipantState: %T", src)
	}
	return nil
}

type NullParticipantState struct {
	ParticipantState ParticipantState `json:"participant_state"`
	Valid            bool             `json:"valid"` // Valid is true if ParticipantState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParticipantState) Scan(value interface{}) error {
	if value == nil {
		ns.ParticipantState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ParticipantState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParticipantState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ParticipantState), nil
}

type TxState string

const (
	TxStateInitiated  TxState = "initiated"
	TxStatePreparing  TxState = "preparing"
	TxStatePrepared   TxState = "prepared"
	TxStateCommitting TxState = "committing"
	TxStateCommitted  TxState = "committed"
	TxStateAborting   TxState = "aborting"
	TxStateAborted    TxState = "aborted"
	TxStateRecovering TxState = "recovering"
	TxStateFailed     TxState = "failed"
)

func (e *TxState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TxState(s)
	case string:
		*e = TxState(s)
	default:
		return fmt.Errorf("unsupported scan type for TxState: %T", src)
	}
	return nil
}

type NullTxState struct {
	TxState TxState `json:"tx_state"`
	Valid   bool    `json:"valid"` // Valid is true if TxState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTxState) Scan(value interface{}) error {
	if value == nil {
		ns.TxState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TxState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTxState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TxState), nil
}

type CompensationLog struct {
	ID                   uuid.UUID          `json:"id"`
	TransactionID        uuid.UUID          `json:"transaction_id"`
	ParticipantID        uuid.UUID          `json:"participant_id"`
	SequenceNo           int64              `json:"sequence_no"`
	ActionType           string             `json:"action_type"`
	CompensationEndpoint string             `json:"compensation_endpoint"`
	RequestPayload       []byte             `json:"request_payload"`
	ResponsePayload      []byte             `json:"response_payload"`
	Status               CompensationStatus `json:"status"`
	ErrorMessage         pgtype.Text        `json:"error_message"`
	RetryCount           int32              `json:"retry_count"`
	ExecutedAt           pgtype.Timestamptz `json:"executed_at"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type DistributedTransaction struct {
	ID                    uuid.UUID          `json:"id"`
	CorrelationID         pgtype.Text        `json:"correlation_id"`
	IdempotencyKey        pgtype.Text        `json:"idempotency_key"`
	State                 TxState            `json:"state"`
	RecoveryNeeded        bool               `json:"recovery_needed"`
	RecoveryAttempts      int32              `json:"recovery_attempts"`
	LastRecoveryAt        pgtype.Timestamptz `json:"last_recovery_at"`
	CoordinatorInstanceID pgtype.Text        `json:"coordinator_instance_id"`
	LeaseExpiresAt        pgtype.Timestamptz `json:"lease_expires_at"`
	PrepareDeadline       pgtype.Timestamptz `json:"prepare_deadline"`
	CommitDeadline        pgtype.Timestamptz `json:"commit_deadline"`
	Version               int64              `json:"version"`
	Metadata              []byte             `json:"metadata"`
	CreatedAt             time.Time          `json:"created_at"`
	UpdatedAt             time.Time          `json:"updated_at"`
	CompletedAt           pgtype.Timestamptz `json:"completed_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
}

type TransactionEvent struct {
	ID            int64       `json:"id"`
	TransactionID uuid.UUID   `json:"transaction_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
	EventType     string      `json:"event_type"`
	EventData     []byte      `json:"event_data"`
	CreatedAt     time.Time   `json:"created_at"`
}

type TransactionParticipant struct {
	ID                   uuid.UUID          `json:"id"`
	TransactionID        uuid.UUID          `json:"transaction_id"`
	ParticipantName      string             `json:"participant_name"`
	ServiceName          string             `json:"service_name"`
	Endpoint             string             `json:"endpoint"`
	State                ParticipantState   `json:"state"`
	PrepareToken         pgtype.Text        `json:"prepare_token"`
	CommitToken          pgtype.Text        `json:"commit_token"`
	PrepareResponse      []byte             `json:"prepare_response"`
	CommitResponse       []byte             `json:"commit_response"`
	AbortResponse        []byte             `json:"abort_response"`
	CompensationEndpoint pgtype.Text        `json:"compensation_endpoint"`
	CompensationPayload  []byte             `json:"compensation_payload"`
	RetryCount           int32              `json:"retry_count"`
	LastRetryAt          pgtype.Timestamptz `json:"last_retry_at"`
	PreparedAt           pgtype.Timestamptz `json:"prepared_at"`
	CommittedAt          pgtype.Timestamptz `json:"committed_at"`
	AbortedAt            pgtype.Timestamptz `json:"aborted_at"`
	CreatedAt            time.Time          `json:"created_at"`
	UpdatedAt            time.Time          `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}
