// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type CompensationEventType string

const (
	CompensationEventTypePREPARESENT  CompensationEventType = "PREPARE_SENT"
	CompensationEventTypeVOTERECEIVED CompensationEventType = "VOTE_RECEIVED"
	CompensationEventTypeCOMMITSENT   CompensationEventType = "COMMIT_SENT"
	CompensationEventTypeABORTSENT    CompensationEventType = "ABORT_SENT"
	CompensationEventTypeCOMMITTED    CompensationEventType = "COMMITTED"
	CompensationEventTypeABORTED      CompensationEventType = "ABORTED"
)

func (e *CompensationEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompensationEventType(s)
	case string:
		*e = CompensationEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for CompensationEventType: %T", src)
	}
	return nil
}

type NullCompensationEventType struct {
	CompensationEventType CompensationEventType `json:"compensation_event_type"`
	Valid                 bool                  `json:"valid"` // Valid is true if CompensationEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompensationEventType) Scan(value interface{}) error {
	if value == nil {
		ns.CompensationEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompensationEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompensationEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompensationEventType), nil
}

type ParticipantState string

const (
	ParticipantStatePENDING   ParticipantState = "PENDING"
	ParticipantStatePREPARED  ParticipantState = "PREPARED"
	ParticipantStateCOMMITTED ParticipantState = "COMMITTED"
	ParticipantStateABORTED   ParticipantState = "ABORTED"
)

func (e *ParticipantState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ParticipantState(s)
	case string:
		*e = ParticipantState(s)
	default:
		return fmt.Errorf("unsupported scan type for ParticipantState: %T", src)
	}
	return nil
}

type NullParticipantState struct {
	ParticipantState ParticipantState `json:"participant_state"`
	Valid            bool             `json:"valid"` // Valid is true if ParticipantState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParticipantState) Scan(value interface{}) error {
	if value == nil {
		ns.ParticipantState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ParticipantState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParticipantState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ParticipantState), nil
}

type TransactionState string

const (
	TransactionStatePREPARING  TransactionState = "PREPARING"
	TransactionStatePREPARED   TransactionState = "PREPARED"
	TransactionStateCOMMITTING TransactionState = "COMMITTING"
	TransactionStateCOMMITTED  TransactionState = "COMMITTED"
	TransactionStateABORTING   TransactionState = "ABORTING"
	TransactionStateABORTED    TransactionState = "ABORTED"
)

func (e *TransactionState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionState(s)
	case string:
		*e = TransactionState(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionState: %T", src)
	}
	return nil
}

type NullTransactionState struct {
	TransactionState TransactionState `json:"transaction_state"`
	Valid            bool             `json:"valid"` // Valid is true if TransactionState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionState) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionState), nil
}

type CompensationLog struct {
	ID            int32                 `json:"id"`
	TransactionID uuid.UUID             `json:"transaction_id"`
	EventType     CompensationEventType `json:"event_type"`
	ParticipantID sql.NullString        `json:"participant_id"`
	Payload       pqtype.NullRawMessage `json:"payload"`
	CreatedAt     time.Time             `json:"created_at"`
}

type Participant struct {
	TransactionID uuid.UUID        `json:"transaction_id"`
	ParticipantID string           `json:"participant_id"`
	Endpoint      string           `json:"endpoint"`
	State         ParticipantState `json:"state"`
	VotedAt       sql.NullTime     `json:"voted_at"`
}

type Transaction struct {
	ID        uuid.UUID        `json:"id"`
	State     TransactionState `json:"state"`
	CreatedAt time.Time        `json:"created_at"`
	UpdatedAt time.Time        `json:"updated_at"`
	TimeoutAt time.Time        `json:"timeout_at"`
}
