// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: participants.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnpreparedParticipants = `-- name: CountUnpreparedParticipants :one
SELECT COUNT(*)
FROM transaction_participants
WHERE transaction_id = $1
AND state != 'prepared'
`

func (q *Queries) CountUnpreparedParticipants(ctx context.Context, transactionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnpreparedParticipants, transactionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const markParticipantAborted = `-- name: MarkParticipantAborted :exec
UPDATE transaction_participants
SET
    state = 'aborted',
    aborted_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkParticipantAborted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markParticipantAborted, id)
	return err
}

const markParticipantCommitted = `-- name: MarkParticipantCommitted :exec
UPDATE transaction_participants
SET
    state = 'committed',
    committed_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkParticipantCommitted(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markParticipantCommitted, id)
	return err
}

const markParticipantPrepared = `-- name: MarkParticipantPrepared :exec
UPDATE transaction_participants
SET
    state = 'prepared',
    prepare_token = $2,
    prepared_at = now(),
    updated_at = now()
WHERE id = $1
`

type MarkParticipantPreparedParams struct {
	ID           uuid.UUID   `json:"id"`
	PrepareToken pgtype.Text `json:"prepare_token"`
}

func (q *Queries) MarkParticipantPrepared(ctx context.Context, arg MarkParticipantPreparedParams) error {
	_, err := q.db.Exec(ctx, markParticipantPrepared, arg.ID, arg.PrepareToken)
	return err
}

const registerParticipant = `-- name: RegisterParticipant :one
INSERT INTO transaction_participants (
    id,
    transaction_id,
    participant_name,
    service_name,
    endpoint,
    state
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    'registered'
)
RETURNING id, transaction_id, participant_name, service_name, endpoint, state, prepare_token, commit_token, prepare_response, commit_response, abort_response, compensation_endpoint, compensation_payload, retry_count, last_retry_at, prepared_at, committed_at, aborted_at, created_at, updated_at, deleted_at
`

type RegisterParticipantParams struct {
	ID              uuid.UUID `json:"id"`
	TransactionID   uuid.UUID `json:"transaction_id"`
	ParticipantName string    `json:"participant_name"`
	ServiceName     string    `json:"service_name"`
	Endpoint        string    `json:"endpoint"`
}

func (q *Queries) RegisterParticipant(ctx context.Context, arg RegisterParticipantParams) (TransactionParticipant, error) {
	row := q.db.QueryRow(ctx, registerParticipant,
		arg.ID,
		arg.TransactionID,
		arg.ParticipantName,
		arg.ServiceName,
		arg.Endpoint,
	)
	var i TransactionParticipant
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ParticipantName,
		&i.ServiceName,
		&i.Endpoint,
		&i.State,
		&i.PrepareToken,
		&i.CommitToken,
		&i.PrepareResponse,
		&i.CommitResponse,
		&i.AbortResponse,
		&i.CompensationEndpoint,
		&i.CompensationPayload,
		&i.RetryCount,
		&i.LastRetryAt,
		&i.PreparedAt,
		&i.CommittedAt,
		&i.AbortedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
