// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createCompensationEvent = `-- name: CreateCompensationEvent :exec
INSERT INTO compensation_log (transaction_id, event_type, participant_id, payload)
VALUES ($1, $2, $3, $4)
`

type CreateCompensationEventParams struct {
	TransactionID uuid.UUID             `json:"transaction_id"`
	EventType     CompensationEventType `json:"event_type"`
	ParticipantID sql.NullString        `json:"participant_id"`
	Payload       pqtype.NullRawMessage `json:"payload"`
}

func (q *Queries) CreateCompensationEvent(ctx context.Context, arg CreateCompensationEventParams) error {
	_, err := q.db.ExecContext(ctx, createCompensationEvent,
		arg.TransactionID,
		arg.EventType,
		arg.ParticipantID,
		arg.Payload,
	)
	return err
}

const createParticipant = `-- name: CreateParticipant :exec
INSERT INTO participants (transaction_id, participant_id, endpoint, state)
VALUES ($1, $2, $3, $4)
`

type CreateParticipantParams struct {
	TransactionID uuid.UUID        `json:"transaction_id"`
	ParticipantID string           `json:"participant_id"`
	Endpoint      string           `json:"endpoint"`
	State         ParticipantState `json:"state"`
}

func (q *Queries) CreateParticipant(ctx context.Context, arg CreateParticipantParams) error {
	_, err := q.db.ExecContext(ctx, createParticipant,
		arg.TransactionID,
		arg.ParticipantID,
		arg.Endpoint,
		arg.State,
	)
	return err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (state, updated_at, timeout_at)
VALUES ($1, $2, $3)
RETURNING id, state, created_at, updated_at, timeout_at
`

type CreateTransactionParams struct {
	State     TransactionState `json:"state"`
	UpdatedAt time.Time        `json:"updated_at"`
	TimeoutAt time.Time        `json:"timeout_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction, arg.State, arg.UpdatedAt, arg.TimeoutAt)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TimeoutAt,
	)
	return i, err
}

const getCompensationEventsByTransaction = `-- name: GetCompensationEventsByTransaction :many
SELECT id, transaction_id, event_type, participant_id, payload, created_at
FROM compensation_log
WHERE transaction_id = $1
ORDER BY created_at
`

func (q *Queries) GetCompensationEventsByTransaction(ctx context.Context, transactionID uuid.UUID) ([]CompensationLog, error) {
	rows, err := q.db.QueryContext(ctx, getCompensationEventsByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompensationLog
	for rows.Next() {
		var i CompensationLog
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.EventType,
			&i.ParticipantID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredTransactions = `-- name: GetExpiredTransactions :many
SELECT id, state, created_at, updated_at, timeout_at
FROM transactions
WHERE timeout_at < now() AND state NOT IN ('COMMITTED', 'ABORTED')
`

func (q *Queries) GetExpiredTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, getExpiredTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.State,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TimeoutAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getParticipantsByTransaction = `-- name: GetParticipantsByTransaction :many
SELECT transaction_id, participant_id, endpoint, state, voted_at
FROM participants
WHERE transaction_id = $1
`

func (q *Queries) GetParticipantsByTransaction(ctx context.Context, transactionID uuid.UUID) ([]Participant, error) {
	rows, err := q.db.QueryContext(ctx, getParticipantsByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Participant
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.TransactionID,
			&i.ParticipantID,
			&i.Endpoint,
			&i.State,
			&i.VotedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, state, created_at, updated_at, timeout_at
FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransaction(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TimeoutAt,
	)
	return i, err
}

const updateParticipantState = `-- name: UpdateParticipantState :exec
UPDATE participants
SET state = $3, voted_at = $4
WHERE transaction_id = $1 AND participant_id = $2
`

type UpdateParticipantStateParams struct {
	TransactionID uuid.UUID        `json:"transaction_id"`
	ParticipantID string           `json:"participant_id"`
	State         ParticipantState `json:"state"`
	VotedAt       sql.NullTime     `json:"voted_at"`
}

func (q *Queries) UpdateParticipantState(ctx context.Context, arg UpdateParticipantStateParams) error {
	_, err := q.db.ExecContext(ctx, updateParticipantState,
		arg.TransactionID,
		arg.ParticipantID,
		arg.State,
		arg.VotedAt,
	)
	return err
}

const updateTransactionState = `-- name: UpdateTransactionState :exec
UPDATE transactions
SET state = $2, updated_at = $3
WHERE id = $1
`

type UpdateTransactionStateParams struct {
	ID        uuid.UUID        `json:"id"`
	State     TransactionState `json:"state"`
	UpdatedAt time.Time        `json:"updated_at"`
}

func (q *Queries) UpdateTransactionState(ctx context.Context, arg UpdateTransactionStateParams) error {
	_, err := q.db.ExecContext(ctx, updateTransactionState, arg.ID, arg.State, arg.UpdatedAt)
	return err
}
