// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcquireRecoveryLease(ctx context.Context, arg AcquireRecoveryLeaseParams) (DistributedTransaction, error)
	AppendCompensationLog(ctx context.Context, arg AppendCompensationLogParams) (CompensationLog, error)
	AppendTransactionEvent(ctx context.Context, arg AppendTransactionEventParams) error
	CompleteCompensation(ctx context.Context, arg CompleteCompensationParams) error
	CompleteTransaction(ctx context.Context, id uuid.UUID) error
	CountUnpreparedParticipants(ctx context.Context, transactionID uuid.UUID) (int64, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (DistributedTransaction, error)
	FailCompensation(ctx context.Context, arg FailCompensationParams) error
	GetPendingCompensations(ctx context.Context, limit int32) ([]CompensationLog, error)
	GetRecoverableTransactions(ctx context.Context, limit int32) ([]DistributedTransaction, error)
	GetStalledPreparedTransactions(ctx context.Context) ([]DistributedTransaction, error)
	GetTransaction(ctx context.Context, id uuid.UUID) (DistributedTransaction, error)
	GetTransactionParticipants(ctx context.Context, transactionID uuid.UUID) ([]TransactionParticipant, error)
	GetTransactionTimeline(ctx context.Context, transactionID uuid.UUID) ([]TransactionEvent, error)
	IncrementRecoveryAttempts(ctx context.Context, id uuid.UUID) error
	MarkCompensationRunning(ctx context.Context, id uuid.UUID) error
	MarkParticipantAborted(ctx context.Context, id uuid.UUID) error
	MarkParticipantCommitted(ctx context.Context, id uuid.UUID) error
	MarkParticipantPrepared(ctx context.Context, arg MarkParticipantPreparedParams) error
	RegisterParticipant(ctx context.Context, arg RegisterParticipantParams) (TransactionParticipant, error)
	RenewRecoveryLease(ctx context.Context, arg RenewRecoveryLeaseParams) error
	TransitionTransactionState(ctx context.Context, arg TransitionTransactionStateParams) (DistributedTransaction, error)
}

var _ Querier = (*Queries)(nil)
