// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recovery.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getRecoverableTransactions = `-- name: GetRecoverableTransactions :many
SELECT id, correlation_id, idempotency_key, state, recovery_needed, recovery_attempts, last_recovery_at, coordinator_instance_id, lease_expires_at, prepare_deadline, commit_deadline, version, metadata, created_at, updated_at, completed_at, deleted_at
FROM distributed_transactions
WHERE recovery_needed = true
AND state IN (
    'preparing',
    'prepared',
    'committing',
    'aborting'
)
ORDER BY created_at
LIMIT $1
`

func (q *Queries) GetRecoverableTransactions(ctx context.Context, limit int32) ([]DistributedTransaction, error) {
	rows, err := q.db.Query(ctx, getRecoverableTransactions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DistributedTransaction
	for rows.Next() {
		var i DistributedTransaction
		if err := rows.Scan(
			&i.ID,
			&i.CorrelationID,
			&i.IdempotencyKey,
			&i.State,
			&i.RecoveryNeeded,
			&i.RecoveryAttempts,
			&i.LastRecoveryAt,
			&i.CoordinatorInstanceID,
			&i.LeaseExpiresAt,
			&i.PrepareDeadline,
			&i.CommitDeadline,
			&i.Version,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStalledPreparedTransactions = `-- name: GetStalledPreparedTransactions :many
SELECT id, correlation_id, idempotency_key, state, recovery_needed, recovery_attempts, last_recovery_at, coordinator_instance_id, lease_expires_at, prepare_deadline, commit_deadline, version, metadata, created_at, updated_at, completed_at, deleted_at
FROM distributed_transactions
WHERE state = 'prepared'
AND updated_at < now() - interval '30 seconds'
`

func (q *Queries) GetStalledPreparedTransactions(ctx context.Context) ([]DistributedTransaction, error) {
	rows, err := q.db.Query(ctx, getStalledPreparedTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DistributedTransaction
	for rows.Next() {
		var i DistributedTransaction
		if err := rows.Scan(
			&i.ID,
			&i.CorrelationID,
			&i.IdempotencyKey,
			&i.State,
			&i.RecoveryNeeded,
			&i.RecoveryAttempts,
			&i.LastRecoveryAt,
			&i.CoordinatorInstanceID,
			&i.LeaseExpiresAt,
			&i.PrepareDeadline,
			&i.CommitDeadline,
			&i.Version,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionParticipants = `-- name: GetTransactionParticipants :many
SELECT id, transaction_id, participant_name, service_name, endpoint, state, prepare_token, commit_token, prepare_response, commit_response, abort_response, compensation_endpoint, compensation_payload, retry_count, last_retry_at, prepared_at, committed_at, aborted_at, created_at, updated_at, deleted_at
FROM transaction_participants
WHERE transaction_id = $1
`

func (q *Queries) GetTransactionParticipants(ctx context.Context, transactionID uuid.UUID) ([]TransactionParticipant, error) {
	rows, err := q.db.Query(ctx, getTransactionParticipants, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionParticipant
	for rows.Next() {
		var i TransactionParticipant
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.ParticipantName,
			&i.ServiceName,
			&i.Endpoint,
			&i.State,
			&i.PrepareToken,
			&i.CommitToken,
			&i.PrepareResponse,
			&i.CommitResponse,
			&i.AbortResponse,
			&i.CompensationEndpoint,
			&i.CompensationPayload,
			&i.RetryCount,
			&i.LastRetryAt,
			&i.PreparedAt,
			&i.CommittedAt,
			&i.AbortedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementRecoveryAttempts = `-- name: IncrementRecoveryAttempts :exec
UPDATE distributed_transactions
SET
    recovery_attempts = recovery_attempts + 1,
    last_recovery_at = now()
WHERE id = $1
`

func (q *Queries) IncrementRecoveryAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementRecoveryAttempts, id)
	return err
}
